{
 "title": "OpenWhisk - Top Namespaces",
 "tags": [ "openwhisk" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Top Namespaces",
   "type": "table",
   "description": "Top namespaces by activation count",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(namespace)(increase(openwhisk_action_activations_total[${__range_s}s])))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "description": "Top memory sizes specified (in MB)",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(memory)(increase(openwhisk_action_activations_total[${__range_s}s])))"
    }
   ]
  },
  {
   "title": "Kind",
   "type": "table",
   "description": "Top activation 'kind'",
   "gridPos": { "h": 10, "w": 5, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(kind)(increase(openwhisk_action_activations_total[${__range_s}s])))"
    }
   ]
  },
  {
   "title": "Top Actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, sum by(namespace,action,kind,memory)(increase(openwhisk_action_activations_total[${__range_s}s])))"
    }
   ]
  }
 ]
}